### PyTorch's tensor library

In [1]:
import torch

In [5]:
tensor0d = torch.tensor(1)
tensor1d = torch.tensor([1, 2])
tensor2d = torch.tensor([[1, 2], [3, 4]])
tensor3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [7]:
# 32-bit precision for deep learning, GPU architectures designed for this and better efficiency overall
floatvec = tensor1d.to(torch.float32)
print(floatvec.dtype)

torch.float32


In [14]:
tensor2d.shape

torch.Size([2, 2])

In [15]:
# tensor2d.reshape(1, 4) -- less common than view
tensor2d.view(1, 4)

tensor([[1, 2, 3, 4]])

In [10]:
tensor2d.shape

torch.Size([2, 2])

In [17]:
tensor2d.T # transpose a tensor, flip it across its diagonal

tensor([[1, 3],
        [2, 4]])

In [18]:
tensor2d.matmul(tensor2d.T)
# tensor2d @ tensor2d.T accomplishes same thing but less common

tensor([[ 5, 11],
        [11, 25]])

In [19]:
# see https://pytorch.org/docs/stable/tensors.html for more operations

### PyTorch's automatic differentiation engine

- a *computation graph* is a directed graph that allows us to express and visualize mathematical expressions

- it lays out the sequence of calculations needed to compute the output of a neural network

In [2]:
# example of a forward pass (prediction step) of a simple logistic regression classifier that returns a score between 0 and 1
# that is compared to the true class label when computing the loss

import torch.nn.functional as F

y = torch.tensor([1.0]) # true label
x1 = torch.tensor([1.1]) # input feature
w1 = torch.tensor([2.2]) # the weight parameter
b = torch.tensor([0.0]) # bias unit

z = x1 * w1 + b # net input
a = torch.sigmoid(z) # activation & output

loss = F.binary_cross_entropy(a, y)
print(loss)

tensor(0.0852)


PyTorch's autograd engine constructions a computation graph in the background by tracking every operation performed on tensors. Then, calling the grad function, we can compute the gradient of the loss with respect to model parameter w1:

In [ ]:
import torch.nn.functional as F
from torch.autograd import grad

y = torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.2], requires_grad=True)
b = torch.tensor([0.0], requires_grad=True)

z = x1 * w1 + b
a = torch.sigmoid(z)

loss = F.binary_cross_entropy(a, y)

grad_L_w1 = grad(loss, w1, retain_graph=True) # by default, PyTorch destroys the computation graph after calculating the gradients to free memory
grad_L_b = grad(loss, b, retain_graph=True)

In [4]:
# resulting values of the loss with respect to the model's parameters:
print(grad_L_w1)
print(grad_L_b)

(tensor([-0.0898]),)
(tensor([-0.0817]),)


In [5]:
# PyTorch provides even more high-level tools to compute the gradients of all the leaf nodes in the graph

loss.backward()

In [6]:
print(w1.grad)
print(b.grad)

tensor([-0.0898])
tensor([-0.0817])


### Implementing multilayer neural networks