### PyTorch's tensor library

In [4]:
import torch

/Users/jenniferjordache/Developer/ml_with_pytorch_scikit/venv/lib/python3.10/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),


In [5]:
tensor0d = torch.tensor(1)
tensor1d = torch.tensor([1, 2])
tensor2d = torch.tensor([[1, 2], [3, 4]])
tensor3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [7]:
# 32-bit precision for deep learning, GPU architectures designed for this and better efficiency overall
floatvec = tensor1d.to(torch.float32)
print(floatvec.dtype)

torch.float32


In [14]:
tensor2d.shape

torch.Size([2, 2])

In [15]:
# tensor2d.reshape(1, 4) -- less common than view
tensor2d.view(1, 4)

tensor([[1, 2, 3, 4]])

In [10]:
tensor2d.shape

torch.Size([2, 2])

In [17]:
tensor2d.T # transpose a tensor, flip it across its diagonal

tensor([[1, 3],
        [2, 4]])

In [18]:
tensor2d.matmul(tensor2d.T)
# tensor2d @ tensor2d.T accomplishes same thing but less common

tensor([[ 5, 11],
        [11, 25]])

In [19]:
# see https://pytorch.org/docs/stable/tensors.html for more operations

### PyTorch's automatic differentiation engine